version: '3'
services:
    app:
        build:
            context: ../docker/php_apache
            dockerfile: Dockerfile
            args:
                GID: '${GID}'
                UID: '${UID}'
        ports:
            - 80:80
            - 3000:3000
        volumes:
            - .:/home/docker/src
        working_dir: /home/docker/src
        tty: true
        user: '${UID}:${GID}'
        networks:
            - dev
        depends_on:
            - db

    db:
        image: mariadb:10.3
        container_name: mariadb_laravel_vite
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            TZ: 'Asia/Tokyo'
        volumes:
            - ../docker/db/data:/var/lib/mysql
            - ../docker/db/log:/var/log/mysql
            - ../docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
        networks:
            - dev
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    adminer:
        container_name: adminer
        image: adminer:4.8.1
        restart: always
        ports:
            - 8080:8080
        networks:
            - dev
        depends_on:
            - db
networks:
    dev:
        driver: bridge
